<?php
session_start();
header('Access-Control-Allow-Origin: *');

echo json_encode([
    'status' => 'ok',
    "GET" => $_GET,
    "POST" => $_POST,
    "FILES" => $_FILES,
    "METHOD" => $_SERVER['REQUEST_METHOD'],
], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRESERVE_ZERO_FRACTION | JSON_UNESCAPED_LINE_TERMINATORS | JSON_PARTIAL_OUTPUT_ON_ERROR | JSON_INVALID_UTF8_IGNORE | JSON_INVALID_UTF8_SUBSTITUTE | JSON_THROW_ON_ERROR);